//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBHFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_assessment_type_master_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_content_assessment_type_master_details()
        {
            this.tbl_kpi_scoring_master_details = new HashSet<tbl_kpi_scoring_master_details>();
        }
    
        public int ID_Assessment_Type { get; set; }
        public string Content_Assessment_Type { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kpi_scoring_master_details> tbl_kpi_scoring_master_details { get; set; }
    }
}
