//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBHFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kpi_master_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kpi_master_details()
        {
            this.tbl_kpi_scoring_master_details = new HashSet<tbl_kpi_scoring_master_details>();
            this.tbl_user_kpi_data_log = new HashSet<tbl_user_kpi_data_log>();
        }
    
        public int ID_KPI { get; set; }
        public string KPI_Name { get; set; }
        public int ID_Organization { get; set; }
        public int KPI_Type { get; set; }
        public int KPI_SubType { get; set; }
        public string Description { get; set; }
        public int Scoring_Logic { get; set; }
        public int Corebus_KPI_ID { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> game_id { get; set; }
    
        public virtual tbl_organization tbl_organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kpi_scoring_master_details> tbl_kpi_scoring_master_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_user_kpi_data_log> tbl_user_kpi_data_log { get; set; }
    }
}
