//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBHFL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_kpi_data_log
    {
        public int id_user_kpi_data_log { get; set; }
        public int id_user { get; set; }
        public int ID_KPI { get; set; }
        public string KPI_Name { get; set; }
        public string KPI_SubType { get; set; }
        public Nullable<int> game_id { get; set; }
        public string assessment_platform { get; set; }
        public int ID_Scoring_Matrix { get; set; }
        public int ID_Assessment_Type { get; set; }
        public int Content_Assessment_ID { get; set; }
        public int AttemptNo { get; set; }
        public int? mastery_score { get; set; }
        public double? scoring_value { get; set; }
        public decimal points_scored { get; set; }
        public string IsActive { get; set; }
        public string UserID { get; set; }
        public bool IsRecordProcessed { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> TotalQuestions { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual tbl_kpi_master_details tbl_kpi_master_details { get; set; }
        public virtual tbl_kpi_scoring_master_details tbl_kpi_scoring_master_details { get; set; }
    }
}
